moviedetail/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'moviedetail'

urlpatterns = [
    path('movie-details/',views.moviedetail, name='movie-details'),
    path('movie-details/<int:movieid>/',views.moviedetail,name='movie-details'),
    path('movie-details/<int:id>/',views.toprating,name='movie-details'),
]

register/urls.py
from django.contrib import admin
from django.urls import path , re_path
from .import views
from django.contrib.auth import views as auth_views
from .views import *
from django.conf import settings

from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('register/',views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password_reset/complete/',custom.as_view(),name='password_reset_complete'),
    
]

webproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static  import static
from django.contrib.auth import views 
from websiteapp.views import error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('websiteapp.urls','websiteapp'),namespace='websiteapp')),
    path('register/',include('register.urls')),
    path('<str:movieid>/',include('websiteapp.urls')),
    #path('password_reset/',views.PasswordResetView.as_view(),name='password_reset'),
    #path('password_reset/done/',views.PasswordResetDoneView,name='password_reset_done'),
    #path('password_reset/confirm/<uidb64>/<token>/',views.PasswordResetConfirmView,name='password_reset_confirm'),
    #path('password_reset/complete/',views.PasswordResetCompleteView,name='password_reset_complete'),

    path('',include('django.contrib.auth.urls'),name='password_reset'),
    
    
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL , document_root= settings.MEDIA_ROOT)

handler404 = 'websiteapp.views.error_404'

websiteapp/urls.py
from django.contrib import admin
from django.urls import path,re_path
from .import views
from .views import *
from register.views import logout
from  django.contrib.auth import views as auth_views

from django.conf import settings

from django.views.static import serve

app_name = "websiteapp"
app_name = "toprating"
app_name = "register"
urlpatterns = [
    path('',views.index, name='index'),
    path('register/',views.register, name='register'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',custom.as_view(),name='password_reset_complete'),
    path('password_change/',auth_views.PasswordChangeView.as_view()),
    path('favouritelist/',views.favlist,name='favlist'),
    path('deleterating/<int:deleteid>/',views.ratingdelete,name='rating-delete'),
    path('like/<str:movieid>/<int:id>/',views.addlike,name='addlike'),
    path('search',views.search,name='search'),
    path('collection-list/<int:collection_id>/',views.display_collection_movies,name='collection'),
    path('discover/<str:genre_name>/<str:genreid>/<str:section>/',views.discover,name='discover-genre'),
    path('register/',views.register, name='register'),
    path('logout/',views.logout,name='logout'),
    path('myprofile/<int:id>/',views.myprofile,name='myprofile'),
    #path('info/<int:user_id>/update/',views.update_profile,name='info-update'),
    path('createprofile/<int:id>/',createprofile.as_view(),name='createprofile'),
    path('profile/<int:pk>/update/',profileupdateview.as_view(),name='update-profile'),
    path('favouritelist/',views.favlist,name='favlist'),
    path('allshows/<str:section>/<int:id>/',views.allshows,name='allshows'),
    path('<str:movieid>/<int:id>/',MovieDetailView.as_view(),name='movie-details'),
    #path('<str:movieid>/tmdb/',MovieDetailView.as_view(),name='movie-details'),
    path('add-comment/<str:movieid>/<int:id>/',views.post_comment,name='add-comment'),
    path('add-Rating/<str:movieid>/<int:id>/',views.post_rating,name='add-rating'),
    path('delete-Rating/<str:movieid>/<int:id>/<int:did>/',views.ratedelete,name='delete-rating'),
    path('delete-comment/<str:movieid>/<int:id>/<int:did>/',views.comment_delete,name='delete-comment'),
    path('deletecomment/<int:delid>/<int:id>/',views.commentdelete,name='comment-delete'),
    path('add-to-favourite/<str:movieid>/<int:id>/',views.addfavourite_tmdb,name='add-to-favourite'),
    path('addfavourite/<str:movieid>/<int:id>/',views.addfavourite,name='addfavourite'),
    path('register/',views.register, name='register'),
    path('register/login/',views.login,name='login'),
    path('toprating/<str:movd>/',views.toprating,name='toprating'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

moviedetail/models.py
from django.db import models

# Create your models here.

moviedetail/views.py
from django.shortcuts import render,get_object_or_404

from django.contrib.auth.models import User

from websiteapp.models import *

from django.http import HttpResponse

def moviedetail(request,movieid):

    detail = moviedetailpage.objects.all()

    det = moviedetailpage.objects.get(pk=movieid)

    context = {'detail':detail}
     
    return render (request,'movie-details/movie-details.html',context,{'det':det})

def toprating (request,id):

    futail = toprated.objects.all()

    fut = get_object_or_404(toprated,pk=id)

    context = {'futail':futail}

    context = {'fut':fut}

    return render (request,'websiteapp/movie-details.html',context)

websiteapp/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from .models import *
from django.contrib.auth.views import PasswordChangeView,PasswordResetCompleteView
from django.contrib import auth
from.forms import commentsform,ratingform,profileform,profileupdate,commentform,rateform
from django.urls import reverse_lazy,reverse
from django.views.generic import DetailView,CreateView,View, UpdateView
from django.views import generic
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from register.views import register
from django.db.models import Q,Avg,Func
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect , JsonResponse
from django.template.loader import render_to_string
from.forms import commentsform
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserChangeForm
import requests
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib.auth import get_user_model
import os
from django import template
from django.utils.text import slugify


key = os.environ.get('key')


def error_404(request,exception):
    return render(request,'websiteapp/movie-not-found.html')


class profileupdateview(LoginRequiredMixin,generic.UpdateView):

    model = profile
    template_name = 'websiteapp/updateprofile.html'
    fields = ['bio', 'dp', 'insta_url', 'fb_url','twitter_url','youtube_url','github_url']
    success_url = reverse_lazy('websiteapp:index')

    def get_object(self, queryset=None):
        return self.request.user.profile



def usercomment(request,videoid):

    if request.method == 'POST':

        form = commentsform(request.POST)

        if form.is_valid :

            form.save()
            messages.success(request,'Posted succesfully')
            
            return HttpResponseRedirect('/usercomment')
    else:


        form = commentsform

    sut = get_object_or_404(topseries,video=videoid)

    sure = topseries.objects.all()


    return render(request,'websiteapp/usercomment.html',{'form':form,'sut':sut,'sure':sure})


def index(request):

    User = get_user_model()

    superuser = User.objects.filter(is_superuser=True).first()


    detail = newmovies.objects.all()

    futail = topmovies.objects.all()[:8]

    series = topseries.objects.all()[:4]

    anime = topanimes.objects.all()[:4]

    
    api_urls = [
        f'https://api.themoviedb.org/3/movie/popular?api_key={key}',
        # Add more API URLs here for additional movie details
    ]
    genre_url = f'https://api.themoviedb.org/3/genre/movie/list?api_key={key}'
    genre_serie_url = f'https://api.themoviedb.org/3/genre/tv/list?api_key={key}'
    series_api = f'https://api.themoviedb.org/3/tv/top_rated?api_key={key}'
    lan_url_m = f'https://api.themoviedb.org/3/configuration/languages?api_key={key}'
    lan_response = requests.get(lan_url_m)
    lan_data = lan_response.json()
    
    lan_list = []
    for lan in lan_data:
        lan_details = {
            
            'iso_639_1': lan['iso_639_1'],
            'english_name' : lan['english_name'],
            'name' : lan['name'],
        }
        lan_list.append(lan_details)
    response = requests.get(series_api)
    series_data = response.json()
    series = series_data['results']
    
    genre_response = requests.get(genre_url)

    genre_data = genre_response.json()
    genres = genre_data['genres']

    genre_res = requests.get(genre_serie_url)

    genres_data = genre_res.json()

    genress = genres_data['genres']

    upcoming_url = f'https://api.themoviedb.org/3/movie/upcoming?api_key={key}'
    upcoming_response = requests.get(upcoming_url)
    upcoming_data = upcoming_response.json()
    upcomings = upcoming_data['results']
    movie_list = []
    series_list = []
    upcoming_list = []
    genre_list = []
    genre_list_2 = []
    base_image_url = 'https://image.tmdb.org/t/p/w500'
    
    
    for genre in genres:
        
        genre_details = {
            'id' : genre['id'],
            'name' : genre['name'],
        }
        genre_list.append(genre_details)
    
    for gen in genress:
         
        genres_details = {
            'id' : gen['id'],
            'name' : gen['name'],
        }
        genre_list_2.append(genres_details)

    for api_url in api_urls:
        response = requests.get(api_url)
        movie_data = response.json()
        movies = movie_data['results']  # Assuming the movie list is under 'results' key

        for movie in movies:
            poster_path = movie.get('poster_path')
            backdrop_path = movie.get('backdrop_path')
            #print(backdrop_path,poster_path)
            #complete_poster_url = base_image_url + poster_path  # Complete URL for the movie poster
            #complete_poster_url_2 = base_image_url + backdrop_path
            #print(f"Movie: {movie['title']}")
            #print(f"Poster URL: {complete_poster_url}")

            movie_details = {
                
                'id' : movie['id'],
                'title': movie['title'],
                'vote_average': movie['vote_average'],
                'release_date': movie['release_date'],
                'poster_path': base_image_url+ str(movie.get('poster_path')),
                'backdrop_path' : base_image_url+ str(movie.get('backdrop_path')),
                'overview' : movie['overview'],
                'popularity' : movie['popularity'],
            }
            movie_list.append(movie_details)

    for serie in series:

                poster = serie['poster_path']
                backdrop_path = serie['backdrop_path']
                complete_poster_url = base_image_url + poster 
                complete_poster_url_2 = base_image_url + backdrop_path

                series_details = {
                    'id' : serie['id'],
                    'title': serie['name'],
                    'vote_average': serie['vote_average'],
                    'release_date': serie['first_air_date'],
                    'poster_path': complete_poster_url,
                    'backdrop_path' : complete_poster_url_2,
                    'overview' : serie['overview'],
                    'popularity' : serie['popularity'],
                    #'genre_names' : genre_names,
                }

                series_list.append(series_details)
    
    for upcoming in upcomings:
         
            upcoming_details = {
                    'id' : upcoming['id'],
                    'title': upcoming['title'],
                    'vote_average': upcoming['vote_average'],
                    'release_date': upcoming['release_date'],
                    'poster_path': base_image_url + str(upcoming.get('poster_path')),
                    'backdrop_path' : base_image_url + str(upcoming.get('backdrop_path')),
                    'overview' : upcoming['overview'],
                    'popularity' : upcoming['popularity'],
            }
            upcoming_list.append(upcoming_details)

    context = {'detail': detail,'futail':futail,'series':series,'anime':anime,'movies': movie_list,'series':series_list,'upcomings':upcoming_list,'genres':genre_list,'genress':genre_list_2,'lan_m':lan_list,'suser':superuser}

    return render(request, 'websiteapp/index.html',context)

def register(request):

    return render(request,'register/register.html')

def discover(request,genre_name,genreid,section):

    time = 'day'

    genre_url = f'https://api.themoviedb.org/3/discover/movie?api_key={key}&with_genres={genreid},'

    genre_serie = f'https://api.themoviedb.org/3/discover/tv?api_key={key}&with_genres={genreid}'

    movie_sort = f'https://api.themoviedb.org/3/discover/movie?api_key={key}&with_original_language={genre_name}'

    series_sort = f'https://api.themoviedb.org/3/discover/tv?api_key={key}&with_original_language={genre_name}'

    trend_url = f'https://api.themoviedb.org/3/trending/movie/{time}?api_key={key}'

    trend_u = f'https://api.themoviedb.org/3/trending/tv/{time}?api_key={key}'


    base_image_url = 'https://image.tmdb.org/t/p/w500'

    genre_list = []
    genre_list_serie =[]
    lan_list_m = []
    lan_list_s = []
    trend_m = []
    trend_s = []

    trend = requests.get(trend_u)

    trend_data = trend.json()

    trend_series = trend_data['results']

    trend_response = requests.get(trend_url)

    trend_Data = trend_response.json()

    trend_movies = trend_Data['results']

    genre_response = requests.get(genre_url)

    genre_data = genre_response.json()

    genres = genre_data['results']

    genre_res =requests.get(genre_serie)

    genre_res_data = genre_res.json()

    genre_series = genre_res_data['results']

    language_response = requests.get(movie_sort)
    language_data = language_response.json()
    language_m = language_data['results']

    lan_response = requests.get(series_sort)
    lan_data = lan_response.json()
    lan_s = lan_data['results']

    for m in trend_movies:
        details = {
                    'id' : m['id'],
                    'title': m['title'],
                    'vote_average': m['vote_average'],
                    'release_date': m.get('release_date'),
                    'poster_path': base_image_url + str(m.get('poster_path')),
                    'backdrop_path' : base_image_url + str(m.get('backdrop_path')),
                    'overview' : m['overview'],
                    'popularity' : m['popularity'],
        }
        trend_m.append(details)

    tm = Paginator(trend_m,8)

    page = request.GET.get('page')

    trend_movie = tm.get_page(page)   

    for s in trend_series:
        
            detail = {
                    'id' : s['id'],
                    'title': s['name'],
                    'vote_average': s['vote_average'],

websiteapp/templates/websiteapp/collection_movies.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Cinegracia - Collection{% endblock %}</title>

  <!-- 
    - favicon
  -->
  <link rel="shortcut icon" href="{% static 'cinelogo.png' %}" type="image">

  <!-- 
    - custom css link
  -->
  <link rel="stylesheet" href="{% static 'ass/css/style.css' %}">
  
  


  <!-- 
    - google font link
  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>

<body id="top">


  <!-- 
    - #HEADER
  -->
{% block header %}
  <header class="header" data-header>
    <div class="container">

      

      <a href="/" class="logo">
        <div class="coontainer">
        <img src="{% static 'cinelogo.png'%}" alt="Cinegracia" width="75" height="75" >
        <p class="hero-subtitle-for">Cinegracia</p>
        </div>
        <style>
          .coontainer{
            display: flex;
            align-items: center;
            margin-right: 10px;
          }
          .hero-subtitle-for {
              margin-right: 20px;
              color: var(--citrine);
              font-size: var(--fs-4);
              font-weight: var(--fw-700);
              margin-bottom: 0px;
              margin-left: 5px;
            }

        </style>
      </a>

      <div class="header-actions">

        <button class="search-btn">
          <ion-icon name="search-outline"></ion-icon>
        </button>

        <div class="lang-wrapper">
          <label for="language">
            <ion-icon name="globe-outline"></ion-icon>
          </label>
        </div>
      {% if user.is_authenticated %}
        <li><a class="btn btn-primary" href="{% url  'register:logout'  %}">Logout</a></li>
      {% else %}
      <li><a class="btn btn-primary" href="{% url 'register:register' %}">Sign-Up</a></li>
      {% endif %}
        </ul>



      </div>

      <button class="menu-open-btn" data-menu-open-btn>
        <ion-icon name="reorder-two"></ion-icon>
      </button>
      <nav class="navbar" data-navbar>

        <div class="navbar-top">
          
          <ul class="navbar-list">

            <div class="title-wrapper">
              <a class="hero-subtitle-for">Here's The '{{collection_name}}' Movies</a>
            </div>
          </ul>

          <button class="menu-close-btn" data-menu-close-btn>
            <ion-icon name="close-outline"></ion-icon>
          </button>
          
        </div>
          

      </nav>

    </div>
  </header>
{% endblock %}

 


  <main>
    <article>

     <!-- 
        - #UPCOMING
      -->
      
      <section class="upcoming-1">
        <style>
          .upcoming-1 {
            position: relative;
  padding-top: 50px;
  padding-bottom: 50px;
            }

            .upcoming-1::before {
                 content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: url("https://image.tmdb.org/t/p/original{{ collection_backdrop_path }}") no-repeat;
  background-size: cover;
  background-position: center;
  opacity: 0.3; 
            }

        </style>
{% block content %}
        <br>
        <br>
        <br>
        <br>
        <div class="container">

         

          <ul class="movies-list  ">
    
      {% for det in movies %}
        
            <li>
              <div class="movie-card">
             
                <a href="{%  url 'websiteapp:movie-details' det.title det.id %}">
             
                  <figure class="card-banner">
                    <img src={{det.poster_path}} alt="The Northman movie poster">
                  </figure>
                  
                </a>

                <div class="title-wrapper">
                  
                  <a href="{%  url 'websiteapp:movie-details' det.title|slugify det.id %}">
                    <h3 class="card-title">{{det.title}}</h3>
                  </a>

                  <time datetime="2022">{{det.release_date}}</time>
                </div>

                <div class="card-meta">
                  <div class="badge badge-outline">HD</div>

                  <div class="duration">
                    <ion-icon name="time-outline"></ion-icon>

                    <time datetime="PT137M">{{det.popularity}}</time>
                  </div>

                  <div class="rating">
                    <ion-icon name="star"></ion-icon>

                  <data>{{det.vote_average}}</data>
                  </div>
                </div>
                  
              </div>
            </li>
      {% endfor %}
       
        </div>
      </section>

{% endblock %}
        </div>
        <br>
        <div class="pagination">
          <span class="step-links">
              {% if movies.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ movies.previous_page_number }}">previous</a>
              {% endif %}
      
              <span class="current">
                  Page {{ movies.number }} of {{ movies.paginator.num_pages }}
              </span>
      
              {% if movies.has_next %}
                  <a href="?page={{ movies.next_page_number }}">next</a>
                  <a href="?page={{ movies.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
        </div> 
      </section>
      <br>

    
    <!--<h2 class="cta-title" style="color: white;">{{movies}}</h2>
    <h2 class="cta-title" style="color: white;">Has Previous Page:{{movies.has_previous}}</h2>
    <h2 class="cta-title" style="color: white;">Has Next Page:{{movies.has_next}}</h2>
    <h2 class="cta-title" style="color: white;">Current Page:{{movies.number}}</h2>
    <h2 class="cta-title" style="color: white;">Total Pages:{{movies.paginator.num_pages}}</h2>
    {% if movies.has_previous %}
      <a href="?page=1">&laquo; First</a>
      <a href="?page={{ movies.previous_page_number }}">Previous</a>
    {% endif %} <br>
    <h2 class="cta-title" style="color: white;">Page {{movies.number}} of {{movies.paginator.num_pages}} </h2><br>
    {% if movies.has_next %}
      <a href="?page={{ movies.next_page_number }}">Next</a>
      <a href="?page={{ movies.paginator.num_pages }}">Last &raquo;</a>
    {% endif %} <br>
{% block footer %}-->

      <!-- 
        - #CTA
      -->

      <section class="cta">
        <style>
          .cta {
  background: url("{%static 'ass/assets/images/cta-bg.jpg' %}") no-repeat;
  background-size: cover;
  background-position: center;
  text-align: center;
  padding-block: 50px;
}

        </style>
        <div class="container">

          <div class="title-wrapper">
            <h2 class="cta-title">Trial start first 30 days.</h2>

            <p class="cta-text">
              Enter your email to create or restart your membership.
            </p>
          </div>

          <form action="" class="cta-form">
            <input type="email" name="email" required placeholder="Enter your email" class="email-field">

            <button type="submit" class="cta-form-btn">Get started</button>
          </form>

        </div>
      </section>

    </article>
  </main>





  <!-- 
    - #FOOTER
  -->

  <footer class="footer">

    <div class="footer-top">
      <style>
        .footer-top {
  background: url("{%static 'ass/assets/images/footer-bg.jpg' %}") no-repeat;
  background-size: cover;
  background-position: center;
  padding-block: 80px 50px;
}

      </style>
      <div class="container">

        <div class="footer-brand-wrapper">

          <a href="/" class="logo">
            <div class="coontainer">
            <img src="{% static 'cinelogo.png'%}" alt="Cinegracia" width="75" height="75" >
            <p class="hero-subtitle-for">Cinegracia</p>
            </div>
          </a>
          <ul class="footer-list">

            <li>
              <a href="/" class="footer-link">Home</a>
            </li>

            <li>
              <a href="#" class="footer-link">Movie</a>
            </li>

            <li>
              <a href="#" class="footer-link">TV Show</a>
            </li>

            <li>
              <a href="#" class="footer-link">Web Series</a>
            </li>

            <li>
              <a href="#" class="footer-link">Pricing</a>
            </li>

          </ul>

        </div>

        <div class="divider"></div>

        <div class="quicklink-wrapper">

          <ul class="quicklink-list">

            <li>
              <a href="#" class="quicklink-link">Faq</a>
            </li>

            <li>
              <a href="#" class="quicklink-link">Help center</a>
            </li>

            <li>
              <a href="#" class="quicklink-link">Terms of use</a>
            </li>

            <li>
              <a href="#" class="quicklink-link">Privacy</a>
            </li>

          </ul>

          <ul class="social-list">

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-facebook"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-twitter"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-pinterest"></ion-icon>
              </a>
            </li>

            <li>
              <a href="#" class="social-link">
                <ion-icon name="logo-linkedin"></ion-icon>
              </a>
            </li>

          </ul>

        </div>

      </div>
    </div>

    <div class="footer-bottom">
      <div class="container">

        <p class="copyright">
          &copy; 2022 <a href="#">sudharcruz</a>. All Rights Reserved
        </p>

        <img src="{% static 'ass/assets/images/footer-bottom-img.png' %}" alt="Online banking companies logo" class="footer-bottom-img">

      </div>
    </div>

  </footer>


  <style>
    .movie-card :is(.duration, .rating) {
  display: flex;
  align-items: center;
  gap: 5px;
  color: var(--gainsboro);
  font-size: var(--fs-11);
  font-weight: var(--fw-500);
  }
  
  .movie-card :is(.duration, .rating) ion-icon {
  font-size: 30px; /* Adjust the font-size value to your preference */
  --ionicon-stroke-width: 2px; /* Adjust the stroke width value to your preference */
  color: var(--citrine);
  }
  .pagination {
    display: flex;
    justify-content: center;
    margin-top: 20px;
}

.pagination a {
    color: var(--citrine);
    padding: 8px 16px;
    text-decoration: none;
    border: 1px solid var(--citrine);
    border-radius: 5px;
    transition: background-color 0.3s ease;
}

.pagination a:hover {
    background-color: var(--citrine);
    color: #fff;
}

.pagination .current {
    padding: 8px 16px;
    font-weight: bold;
    color: var(--citrine);
    border: 1px solid var(--citrine);
    border-radius: 5px;
    background-color:black;
}

.pagination .step-links {
    display: flex;
}

.pagination .step-links a {
    margin: 0 5px;
}

  </style>


  <!-- 
    - #GO TO TOP
  -->

  <a href="#top" class="go-top" data-go-top>
    <ion-icon name="chevron-up"></ion-icon>
  </a>





  <!-- 
    - custom js link
  -->
  <script src="{% static 'ass/assets/js/script.js' %}"></script>

  <!-- 
    - ionicon link
  -->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock %}
</body>

</html>

websiteapp/templates/websiteapp/infoupdate.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>info-update Form</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{%static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{%static 'css/style.css' %}">
</head>
<body>

    <div class="main">

        <div class="container">
            <div class="signup-content">
              <form action="" id="signup-form" class="signup-form" method="post" autocomplete="off">
                    {% csrf_token %}
              <h2>Info Update</h2>
                      
              <div class="form-group">
                    <input type="text" class="form-input" name="name" id="name" placeholder="User Name" required />
              </div>
              <div class="form-group">
                    <input type="text" class="form-input" name="First_name" id="first_name" placeholder="First Name" required/>
              </div>
              <div class="form-group">
                    <input type="text" class="form-input" name="Last_name" id="last_name" placeholder="Last Name" required/>
              </div>
              <div class="form-group">
                    <input type="email" class="form-input" name="email" id="email" placeholder="Email" required/>
              </div>
              <div class="form-group">
                    <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                    <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
              </div>
              <div class="form-group">
                  <label for="agree-term" class="label-agree-term"><h4>Already Have an account? Click Login Button Below</h4></label>
              </div>
                    <input type="submit" name="submit" id="submit" class="form-submit submit" value="Update"/>
              </div>
              </form>


                <div>
                  {% include 'websiteapp/messages.html' %}
                </div>
                
            </div>
        </div>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

websiteapp/templates/websiteapp/tmdb-details.html
    {{selected.title}} <br>
    {{selected.overview}} <br>